name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests (optional)
        run: |
          python -m pytest tests/
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ HRKU-AAUHsQr-rQoXg3Ku8B-BlPcLbw5Wn1TLiPR9FNMoASLg_____wz7kFV3nkUv }}
          heroku_app_name: ${{ vera-fombon-app}}
          heroku_email: ${{ vmfombon@yahoo.com }}
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health"
